
---
# VLANs globaux
vlans_switches:
  - { id: 10, name: "VLAN10" }
  - { id: 20, name: "VLAN20" }
  - { id: 30, name: "VLAN30" }
  - { id: 40, name: "VLAN40" }
  - { id: 99, name: "MGMT_S1" }
  - { id: 100, name: "MGMT_S2" }

switches_config:
  SW1:
    trunk_port: "GigabitEthernet0/0"
    access_ports:
      - { name: "GigabitEthernet0/1", vlan: 10 }
      - { name: "GigabitEthernet0/2", vlan: 20 }
      - { name: "GigabitEthernet0/3", vlan: 30 }
      - { name: "GigabitEthernet1/0", vlan: 40 }
  SW2:
    trunk_port: "GigabitEthernet0/0"
    access_ports:
      - { name: "GigabitEthernet0/1", vlan: 10 }
      - { name: "GigabitEthernet0/2", vlan: 20 }
      - { name: "GigabitEthernet0/3", vlan: 30 }
      - { name: "GigabitEthernet1/0", vlan: 40 }

router_subifs:
  # Management (Fa0/1 vers SW1, Fa1/0 vers SW2)
  - { phy: "FastEthernet0/1", vlan: 99, ip: "192.168.99.1", mask: "255.255.255.0" }
  - { phy: "FastEthernet1/0", vlan: 100, ip: "192.168.100.1", mask: "255.255.255.0" }
  # Donn√©es 
  - { phy: "FastEthernet0/1", vlan: 10, ip: "192.168.10.1", mask: "255.255.255.0" }
  - { phy: "FastEthernet0/1", vlan: 30, ip: "192.168.30.1", mask: "255.255.255.0" }
  - { phy: "FastEthernet1/0", vlan: 20, ip: "192.168.20.1", mask: "255.255.255.0" }
  - { phy: "FastEthernet1/0", vlan: 40, ip: "192.168.40.1", mask: "255.255.255.0" }